---

apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: kafka
spec:
  containers:
    - name: kafka-cli
      image: tototoot/kafka-cli:kafka-2.8.0
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-ec", "echo 'Container is ready - $(date -Iseconds)'", "while true; do sleep 10 ; done"]
  restartPolicy: OnFailure
