---

apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
spec:
  containers:
    - name: kafka-cli
      image: totoroot/kafka-cli:2.8.0
      imagePullPolicy: IfNotPresent
      command: ['/bin/sh', '-c', 'while true; do echo "$(date +"%Y-%m-%dT%H:%M:%SZ") - Container is running" && sleep 600; done']
  restartPolicy: OnFailure
